name: quickblox_video
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  meta: ^1.8.0

  # state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  provider: ^6.0.4

  # quickblox
  quickblox_sdk: ^0.7.2
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/